### ISSUE TITLE
TreatmentHistory Function

### ISSUE THREAD

**Issue by Jay-sanjay** [JuliaHealth/OMOPCDMPathways.jl#4]
1. Creates treatment history based on target, event, and exit cohorts.
2. Filters events based on the start and end dates of the target cohort.
3. Calculates duration of treatment eras and gap between treatments.
4. Possibly should return a data frame with columns: personId, indexYear, eventCohortId, eventStartDate, eventEndDate, type, durationEra.

**Comment by TheCedarPrince** [comment]
Closed by #60 -- good work!
